# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5de4b28b8e359f1d5894d7a050f6ee7a3a775aeb67c8ecd0ccd4e6655f957941a57dec369437fe34d389338c44d1d8280af103e7ed8f9510a0c0d5d7d32fa25d

test:
  secret_key_base: 139d2a217b3a2c329b4d6c664cddf3bddd70bbc94b171a3e925d53a8a7e58d2f634f9deeca724da05b91f65105445f586089908addbd28f0603e2d77a12b4c1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
